#!/bin/bash

# general
export USER_PERMISSIONS="rwx"
export OTHERS_PERMISSIONS="rwx"
export PRE_REQ_TEST_FAILURE_STRING="preReq of test had failed"

# session level
export DEFAULT_PRE_REQ_SESSION_FLAGS='-n'
export MASTER_INITTIAL_OS_FREE_SPACE=100
export NFS_LOG_DIR_MIN_SPACE=1500 #3000
export LOCAL_LOG_DIR_MIN_SPACE=1000

# setup level
export DEFAULT_PRE_REQ_SETUP_FLAGS='-wol'
export DEFAULT_MACHINE_OS_FREE_MIN_SPACE=1024

# test level
export DEFAULT_PRE_REQ_TEST_FLAGS='-rcph'
export DEFAULT_MAPRED_LOCAL_DIR_MIN_SPACE=2048
export DEFAULT_HADOOP_TMP_DIR_MIN_SPACE=2048
export DEFAULT_DFS_NAME_DIR_MIN_SPACE=2048
export DEFAULT_DFS_DATA_DIR_MIN_SPACE=2048
export DEFAULT_MAX_CPU_USAGE=0.2
export DEFAULT_MIN_RAM_REQUIRED=32000



