#!/bin/bash

# General
export OWNER_PERMISSIONS="rwx"
export GROUP_PERMISSIONS="rwx"
export OTHERS_PERMISSIONS="rwx"
export PRE_REQ_TEST_FAILURE_STRING="preReq of test had failed"

# Session level
export DEFAULT_PRE_REQ_SESSION_FLAGS='-n'
export DEFAULT_MASTER_INITTIAL_BASE_FREE_SPACE=100
export DEFAULT_NFS_LOG_DIR_MIN_SPACE=1500 #3000
export DEFAULT_LOCAL_LOG_DIR_MIN_SPACE=1000

# Setup level
export DEFAULT_PRE_REQ_SETUP_FLAGS='-wbl'
export DEFAULT_MACHINE_BASE_FREE_MIN_SPACE=1024

# Test level
export DEFAULT_PRE_REQ_TEST_FLAGS='-rcph'
export DEFAULT_MAPRED_LOCAL_DIR_MIN_SPACE=2048
export DEFAULT_HADOOP_TMP_DIR_MIN_SPACE=2048
export DEFAULT_DFS_NAME_DIR_MIN_SPACE=2048
export DEFAULT_DFS_DATA_DIR_MIN_SPACE=2048
export DEFAULT_MAX_CPU_USAGE=0.2
export DEFAULT_MIN_RAM_REQUIRED=16000
export DEFAULT_MIN_INODES_PERCENT=25



