#!/bin/sh
#
# Copyright (C) 2012 Mellanox Technologies
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at:
#  
# http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, 
# either express or implied. See the License for the specific language 
# governing permissions and  limitations under the License.
#
# 
# Written by Avner BenHanoch
# Date: 2013-04-25

RM=/bin/rm

MASTER=${1:-rswbob12}
LOGDIR=${2:-.}


#VERBOSE="--verbose"
VERBOSE=""

TRACKER=tracker
if ! ls $LOGDIR/*$TRACKER* > /dev/null 2> /dev/null
then
	TRACKER=TRACKER # try "TRACKER" instead of "tracker", (for example, in case cloudera)
fi

SLAVEDIR=`dirname $0`

TARFILE=/tmp/`hostname`_daemons.all-logs.tar
$RM -f $TARFILE*

STRIP=`echo $LOGDIR | sed 's/^\///'` # without leading / (if any), because tar doesn't see it


# 1st create an empty archive, than append all files to it - this way tar will survive even if one componenet does not exist
echo "creating: $TARFILE with all daemon's log files..."
tar  --create -f $TARFILE --files-from=/dev/null
tar $VERBOSE --dereference --transform "s,^$STRIP,," --transform "s,^,`hostname`," --append -f $TARFILE  $LOGDIR/*$TRACKER*.* 2> /dev/null || true


# TODO - check that $P is valid !
# in case TaskTracker is from Cloudera CM => take also its cwd with conf and stdout/stderr
P=`ps -Cjava -o pid,cmd | awk '$3 == "-Dproc_tasktracker" {print $1}'`
if [ -n "$P" ] && grep --silent "Autogenerated by Cloudera CM" /proc/$P/cwd/mapred-site.xml 2> /dev/null
then
	tar $VERBOSE --dereference --transform "s,^,`hostname`-tasktracker-," --append -f $TARFILE /proc/$P/cwd/ 2> /dev/null || true
fi

# in case JobTracker is from Cloudera CM => take also its cwd with conf and stdout/stderr
P=`ps -Cjava -o pid,cmd | awk '$3 == "-Dproc_jobtracker" {print $1}'`
if [ -n "$P" ] && grep --silent "Autogenerated by Cloudera CM" /proc/$P/cwd/mapred-site.xml 2> /dev/null
then
	tar $VERBOSE --dereference --transform "s,^,`hostname`-job-tracker-," --append -f $TARFILE /proc/$P/cwd/ 2> /dev/null || true
fi


if [ "`hostname`" != "$MASTER" ]; then
	scp $TARFILE $MASTER:/tmp/ && echo "$TARFILE was scp'ed to $MASTER:/tmp/"
	$RM -f $TARFILE
fi
      
