#!/bin/sh

RM=/bin/rm


MASTER=${1:-rswbob12}
JOB=${2:-201304091252_0008}
LOGDIR=${3:-.}
CONTEXT=${4:-1000}

#VERBOSE="--verbose"
VERBOSE=""

ENDCHAR=x # Don't use g neither t, because they end *.log and *.out
SUFFIX=.job_$JOB.snippet.$ENDCHAR

FILES="$LOGDIR/*tracker*"
SAFEFILES=$FILES[^$ENDCHAR]
OUTFILES=$FILES$SUFFIX
$RM -f $OUTFILES

SLAVEDIR=`dirname $0`
$SLAVEDIR/job-log-collector.awk JOB=$JOB CONTEXT=$CONTEXT SUFFIX=$SUFFIX $SAFEFILES

TARFILE=/tmp/`hostname`_job_$JOB.all-logs.tar
$RM -f $TARFILE*

STRIP=`echo $LOGDIR | sed s/^.//` # without leading /, because tar doesn't see it




# 1st create an empty archive, than append all files to it - this way tar will survive even if one componenet does not exist
echo "creating: $TARFILE with all job's log files..."
tar  --create -f $TARFILE --files-from=/dev/null
#tar $VERBOSE -C $LOGDIR --dereference --transform "s,^$STRIP,`hostname`," --transform "s,.$ENDCHAR$,," --append -f $TARFILE  $LOGDIR/*$JOB* 2>&1 | grep -v "Removing leading" # takes the xml file, plus any snippet we created
tar $VERBOSE --dereference -C $LOGDIR --transform "s,^$STRIP,`hostname`," --transform "s,.$ENDCHAR$,," --append -f $TARFILE  $LOGDIR/*$JOB* 2>&1 | grep -v "Removing leading" # takes the xml file, plus any snippet we created

#echo $TARFLAGS

#tar -C $LOGDIR --dereference --transform "s,^$STRIP,`hostname`," --append -f $TARFILE  $LOGDIR/userlogs/*$JOB* 2>&1 | grep -v "Removing leading" 
tar $VERBOSE --dereference --transform "s,^$STRIP,`hostname`," --append -f $TARFILE  $LOGDIR/userlogs/*$JOB* 2>&1 | grep -v "Removing leading" |  grep -v "File removed before we read it" #temp, remove noise in NFS tests
tar $VERBOSE --dereference --transform "s,^$STRIP,`hostname`," --append -f $TARFILE  $LOGDIR/*tracker*.out 2> /dev/null || true
tar $VERBOSE --dereference --transform "s,^$STRIP,`hostname`," --append -f $TARFILE  $LOGDIR/*tracker*.out*[^$ENDCHAR] 2> /dev/null || true


# TODO - check that $P is valid !
# in case TaskTracker is from Cloudera CM => take also its cwd with conf and stdout/stderr
P=`jps -m | grep TaskTracker | awk '{print $1}'`
if [ -n "$P" ] && grep --silent "Autogenerated by Cloudera CM" /proc/$P/cwd/mapred-site.xml 2> /dev/null
then
	tar $VERBOSE --dereference --transform "s,^,`hostname`-tasktracker-," --append -f $TARFILE /proc/$P/cwd/ 2> /dev/null || true
fi

# in case JobTracker is from Cloudera CM => take also its cwd with conf and stdout/stderr
P=`jps -m | grep JobTracker | awk '{print $1}'`
if [ -n "$P" ] && grep --silent "Autogenerated by Cloudera CM" /proc/$P/cwd/mapred-site.xml 2> /dev/null
then
	tar $VERBOSE --dereference --transform "s,^,`hostname`-job-tracker-," --append -f $TARFILE /proc/$P/cwd/ 2> /dev/null || true
fi


$RM -f $OUTFILES

if [ "`hostname`" != "$MASTER" ]; then
	scp $TARFILE $MASTER:/tmp/ && echo "$TARFILE was scp'ed to $MASTER:/tmp/"
	$RM -f $TARFILE
fi
      

#TARFLAGS="-C $LOGDIR --dereference --transform \"s,^$STRIP,`hostname`,\" $VERBOSE"
#echo TARFLAGS=$TARFLAGS
